name: SCA scan

on:
  push:
    branches: 'main'

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Deployment
      run: go run main.go
