name: SCA scan

on:
  push:
    branches: 'main'

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Scan for package vulnerabilities
      run: CGO_ENABLED=0 go list -json -m all | nancy sleuth --skip-update-check
    - name: Run app
      run: go run main.go
